### ISSUE TITLE
Can't find where is jQuery used

### ISSUE THREAD

**Issue by AdemHodzic** [saasforge/open-source-saas-boilerpate#11]
I've noticed there is jQuery installed as a dependency in package.json but I can't find where it's used.

**Comment by saasforge** [comment]
Sorry for the delay with this issue! Github didn't notify me about the problem.
Okay, back to jQuery.
It's necessarily library for Bootstrap to work normally. So, it's used internally.
Also, there is an example for using it (even it's not used directly), see here:
https://github.com/saasforge/open-source-saas-boilerpate/blob/6f8b4adf9fe5050d448e4f39ef8dfd0a11b75a06/src/app/auth/AuthApp.jsx

**Comment by saasforge** [comment]
Please don't hesitate if you have any questions. We will monitor the issues tab more often :)
