### ISSUE TITLE
flask dbcreate fails

### ISSUE THREAD

**Issue by s13cre13t** [saasforge/open-source-saas-boilerpate#5]
trying to run flask dbcreate fails

cd /saasForge/
flask dbcreate
> Usage: flask [OPTIONS] COMMAND [ARGS]...
> Try "flask --help" for help.
> 
> Error: No such command "dbcreate".

flask --version
> Flask 1.0.2
> Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
> [GCC 9.2.1 20191008]

ubuntu 19.10

**Comment by saasforge** [comment]
Can you please check if your environmental variable has "FLASK_APP=application" var?
Another reason could be some compilation error. For example, if you run "flask run" will you see any errors?

**Comment by saasforge** [comment]
Closed due to inactivity.

**Comment by saasforge** [comment]
Closed due to inactivity.
